# Generated by Django 5.0.2 on 2024-02-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='asset',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
