# Generated by Django 5.0.2 on 2024-02-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_bankaccount_transaction_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='shaba_number',
            field=models.CharField(blank=True, help_text='با IR بنویسید', max_length=26, null=True),
        ),
    ]
