# Generated by Django 5.0.2 on 2024-02-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_transaction_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_balance',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
