# Generated by Django 5.0.2 on 2024-02-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_transaction_share_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank_balance',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=10, null=True),
        ),
    ]
