# Generated by Django 5.0.2 on 2024-02-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_transaction_bank_balance'),
        ('loans', '0004_loan_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installments',
            field=models.ManyToManyField(blank=True, to='loans.installment', verbose_name='also checkout these Installments:'),
        ),
    ]
