# Generated by Django 5.0.2 on 2024-02-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_transaction_installments'),
        ('loans', '0004_loan_bank_account'),
        ('users', '0004_alter_share_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='share_assets',
            field=models.ManyToManyField(blank=True, to='users.share', verbose_name='Shares to increase assets'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='installments',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='loans.installment', verbose_name='also checkout these Installments:'),
        ),
    ]
