# Generated by Django 5.0.2 on 2024-02-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_transaction_notes_transaction_share_assets_and_more'),
        ('loans', '0004_loan_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accounting_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='installments',
            field=models.ManyToManyField(blank=True, to='loans.installment', verbose_name='also checkout these Installments:'),
        ),
    ]
