# Generated by Django 5.0.2 on 2024-02-25 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installments', models.IntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.share')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unsettled', 'Unsettled'), ('paid', 'Paid')], default='unsettled', max_length=10)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.share')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
            ],
        ),
    ]
