# Generated by Django 5.0.2 on 2024-02-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_installment_amount',
            field=models.DecimalField(decimal_places=0, default=400, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='installment_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
