# Generated by Django 5.0.2 on 2024-02-25 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_transaction_bank_account'),
        ('loans', '0003_remove_installment_status_installment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='bank_account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='finance.bankaccount'),
            preserve_default=False,
        ),
    ]
